#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 4 "..\..\Translation\Views\IndexSingleInstance.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    
    #line 1 "..\..\Translation\Views\IndexSingleInstance.cshtml"
    using System.Reflection;
    
    #line default
    #line hidden
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 5 "..\..\Translation\Views\IndexSingleInstance.cshtml"
    using Signum.Engine.Basics;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Translation\Views\IndexSingleInstance.cshtml"
    using Signum.Engine.Translation;
    
    #line default
    #line hidden
    using Signum.Entities;
    
    #line 6 "..\..\Translation\Views\IndexSingleInstance.cshtml"
    using Signum.Entities.Translation;
    
    #line default
    #line hidden
    using Signum.Utilities;
    using Signum.Web;
    
    #line 3 "..\..\Translation\Views\IndexSingleInstance.cshtml"
    using Signum.Web.Translation.Controllers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Translation/Views/IndexSingleInstance.cshtml")]
    public partial class _Translation_Views_IndexSingleInstance_cshtml : System.Web.Mvc.WebViewPage<Dictionary<CultureInfo, TranslatedTypeSummary>>
    {
        public _Translation_Views_IndexSingleInstance_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 8 "..\..\Translation\Views\IndexSingleInstance.cshtml"
  
    Lite<Entity> instance = ViewBag.Instance;
    ViewBag.Title = "{0} - {1}".Formato(instance.ToString(), TranslationMessage.InstanceTranslations.NiceToString());        

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 13 "..\..\Translation\Views\IndexSingleInstance.cshtml"
Write(Html.ScriptCss("~/Translation/Content/Translation.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 15 "..\..\Translation\Views\IndexSingleInstance.cshtml"
 if (Model.IsEmpty())
{

            
            #line default
            #line hidden
WriteLiteral("    <h2>");

            
            #line 17 "..\..\Translation\Views\IndexSingleInstance.cshtml"
   Write(TranslationMessage.NothingToTranslate.NiceToString());

            
            #line default
            #line hidden
WriteLiteral("</h2>   \r\n");

            
            #line 18 "..\..\Translation\Views\IndexSingleInstance.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <h2>");

            
            #line 21 "..\..\Translation\Views\IndexSingleInstance.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n");

            
            #line 22 "..\..\Translation\Views\IndexSingleInstance.cshtml"
    
    var langs = Model.Keys;


            
            #line default
            #line hidden
WriteLiteral("    <table");

WriteLiteral(" class=\"st\"");

WriteLiteral(">\r\n        <tr>\r\n            <th></th>\r\n            <th>");

            
            #line 28 "..\..\Translation\Views\IndexSingleInstance.cshtml"
           Write(TranslationMessage.All.NiceToString());

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n");

            
            #line 29 "..\..\Translation\Views\IndexSingleInstance.cshtml"
            
            
            #line default
            #line hidden
            
            #line 29 "..\..\Translation\Views\IndexSingleInstance.cshtml"
             foreach (var ci in langs)
            {

            
            #line default
            #line hidden
WriteLiteral("                <th>");

            
            #line 31 "..\..\Translation\Views\IndexSingleInstance.cshtml"
               Write(ci.Name);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n");

            
            #line 32 "..\..\Translation\Views\IndexSingleInstance.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tr>\r\n        <tr>\r\n            <th>");

            
            #line 35 "..\..\Translation\Views\IndexSingleInstance.cshtml"
           Write(instance.ToString());

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 38 "..\..\Translation\Views\IndexSingleInstance.cshtml"
           Write(Html.ActionLink(TranslationMessage.View.NiceToString(), (TranslatedInstanceController tc) => tc.ViewEntity(instance, null, true, null)));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n");

            
            #line 40 "..\..\Translation\Views\IndexSingleInstance.cshtml"
            
            
            #line default
            #line hidden
            
            #line 40 "..\..\Translation\Views\IndexSingleInstance.cshtml"
             foreach (var ci in langs)
            {
                var tf = Model[ci];
                

            
            #line default
            #line hidden
WriteLiteral("                <td>\r\n");

            
            #line 45 "..\..\Translation\Views\IndexSingleInstance.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 45 "..\..\Translation\Views\IndexSingleInstance.cshtml"
                     if (ci.Name == TranslatedInstanceLogic.DefaultCulture.Name)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 47 "..\..\Translation\Views\IndexSingleInstance.cshtml"
                         Write(TranslationMessage.None.NiceToString());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 48 "..\..\Translation\Views\IndexSingleInstance.cshtml"
                    }
                    else
                    {
                        
            
            #line default
            #line hidden
            
            #line 51 "..\..\Translation\Views\IndexSingleInstance.cshtml"
                   Write(Html.ActionLink(TranslationMessage.View.NiceToString(), (TranslatedInstanceController tc) => tc.ViewEntity(instance, ci.Name, true, null)));

            
            #line default
            #line hidden
            
            #line 51 "..\..\Translation\Views\IndexSingleInstance.cshtml"
                                                                                                                                                                   

            
            #line default
            #line hidden
WriteLiteral("                        <br />\r\n");

            
            #line 53 "..\..\Translation\Views\IndexSingleInstance.cshtml"
                        if (tf.State != null)
                        {
                            
            
            #line default
            #line hidden
            
            #line 55 "..\..\Translation\Views\IndexSingleInstance.cshtml"
                       Write(Html.ActionLink(TranslationMessage.Sync.NiceToString(), (TranslatedInstanceController tc) => tc.SyncEntity(instance, tf.CultureInfo.Name), new { @class = "status-" + tf.State.ToString() }));

            
            #line default
            #line hidden
            
            #line 55 "..\..\Translation\Views\IndexSingleInstance.cshtml"
                                                                                                                                                                                                                         
                        }
                    }

            
            #line default
            #line hidden
WriteLiteral("                </td>\r\n");

            
            #line 59 "..\..\Translation\Views\IndexSingleInstance.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tr>\r\n    </table>\r\n");

            
            #line 62 "..\..\Translation\Views\IndexSingleInstance.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
